apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
data:
  username: ZWxhc3RpYw==
  password: UEBzc3cwcmQ=
kind: Secret
metadata:
  name: elasticsearch-master-credentials
  namespace: logging
type: Opaque
