apiVersion: v1
kind: Namespace
metadata:
  name: logging
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-eck-demo-es-elastic-user  # <ES helm install release name>-<ES resource-name>-es-elastic-user
  namespace: logging
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
type: Opaque
data:
  elastic: UEBzc3cwcmQ=  # P@ssw0rd
