apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - ../base

secretGenerator:
  - name: elasticsearch-master-credentials
    type: Opaque
    namespace: logging
    literals:
      - username=elastic
      - password=P@ssw0rd
