apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      @id input_tail
      path /var/log/kubernetes/audit.log
      pos_file /var/log/td-agent/audit.log.pos
      tag kube.audit.log
      read_from_head true
      <parse>
        @type json
      </parse>
    </source>

    <match kube.audit.log>
      @type prometheus
      <labels>
        k8s_audit_type ${record['auditAnnotations']['k8s_audit_type']}
        k8s_resource ${record['auditAnnotations']['k8s_resource']}
      </labels>
    </match>
